version: '2'

services:
  erlmur:
    build:
      context: ./docker
      dockerfile: Dockerfile_dev
    ports:
     - "64738:64738/tcp"
     - "64738:64738/udp"
    volumes:
      - .:/src/erlmur
      - rebar3:/root/.cache/rebar3
    working_dir: /src/erlmur
    #environment:
    # - DEBUG=1
    command: rebar3 shell

volumes:
  rebar3:
    driver: local
