name: Erlang CI

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:latest

    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v3
    - name: Compile And Test
      run: just test
